local pieces =  {"#sprite1", "#sprite2"}
local pieceHeight = 960

function init(self) 
	self.speed = 360  -- Speed in pixels/s
end

function update(self, dt) 

	for i, piece in ipairs(pieces) do
		local position = go.get_position(piece)
		print(position.y)
		
		if position.y <= (pieceHeight / -2) then
			position.y = pieceHeight / 2
		end

		position.y = position.y - self.speed * dt 
		go.set_position(position, piece) 
	end

end