local ground_pieces =  {"ground0", "ground1"}
local piece_width = 1280

function init(self) 
	self.speed = 360  -- Speed in pixels/s
end

function update(self, dt) 

	for i, ground_piece in ipairs(ground_pieces) do
		local position = go.get_position(ground_piece)

		if position.x <= (-1 * piece_width) then
			position.x =  position.x + (2 * piece_width)
		end

		position.x = position.x - self.speed * dt 
		go.set_position(position, ground_piece) 
	end

end