function do_game_over_things(self)
	print("iik, peli päättyi")
	msg.post("ui#gui", "game_over")
end



function init(self)
	self.score = 0
end

function on_message(self, message_id, message, sender)
	if message_id == hash("out_of_bounds") then
		do_game_over_things(self)
	elseif message_id == hash("add_score") then
		self.score = self.score + 1
		msg.post("ui#gui", "set_score", { score = self.score })
	end
end
